### ISSUE TITLE
Izjava o avtorstvu

### ISSUE THREAD

**Issue by terrible-solver** [ladisk/latex-templates#7]
Kopije izjave o avtorstvu ni več potrebno vlagati v fizični izvod zaključnega dela, saj je izjava digitalna preko sistema VIS. Predlagam da se stran za vlaganje izjave odstrani iz template-a

**Comment by jankoslavic** [comment]
hvala!

**Comment by jankoslavic** [comment]
je to urejeno @martincesnik @terrible-solver , se lahko ta issue zapre?

**Comment by martincesnik** [comment]
urejeno in skomunicirano s Študentskim referatom
